# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.3
language: objective-c

script:
- set -o pipefail && xcodebuild test -workspace Example/OneStore.xcworkspace -scheme OneStore -sdk iphonesimulator10.1 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
